### PR TITLE
Abstract out clojure.tools.cli

### PR DESCRIPTION
**Pull request by sirmspencer**

### CODE REVIEW

**Comment by rjsheperd** [comment]
#### src/triangulum/build_db.clj
46 - Linter is complaining about shadowing the `namespace` variable

Otherwise, LGTM 👍

**Comment by Kcheung42** [comment]
triangulum.build-db
- Line 6-7: Align :refer
- Line 129: extra space in front of "Print

triangulum.cli
- Line 52: "You can only select one action at a time" might read better?

**Comment by sirmspencer** [comment]
Line 6-7: Align :refer
-- I have been grouping :as and :refer separately.  I also tend to group project imports separately from library imports

**Comment by sirmspencer** [comment]
> #### src/triangulum/build_db.clj
> 46 - Linter is complaining about shadowing the `namespace` variable
> 
> Otherwise, LGTM

Thanks for the observation.  Since I did not change that code, this is out of scope of this PR.  We will want to go back and clear all of those warnings at some point.

**Pull request merged**
