### PR TITLE
Add initial set of new namespaces

### PR DESCRIPTION
**Pull request by sirmspencer**

### CODE REVIEW

**Comment by rjsheperd** [comment]
This is looking great. 👍 

Just some quick things:
1. It would be great if you could add docstrings to the public methods, especially for the `database.clj` methods
2. Not sure if this is possible in this PR, but a project template that could be instantiated with `clj -M:setup` could help lower the friction to getting onboarded (e.g. creates `src/sql`, `src/cljs`, `src/clj` and `resources`, possibly prompts the user for the Database they are using)

**Review by rjsheperd — APPROVED** [review]

**Comment by Kcheung42** [comment]
README.org
- triangulum.logging
  - Mention optional kwargs and defaults
  - Mention logs cleared on a 24 hour period
- triangulum.build-db
  - Mention the folders that the load functions target
  - Mention usage of `toplevel` sql comments (i.e. --NAMESPACE --REQUIRES)

Would it be useful to create unit tests for these ns too?
- triangulum.logging
- triangulum.database


triangulum.logging:
- Line 9: Newline after `output-path` or remove newline on Line:8
- Line 33: log-str doesn't support optional kwargs like log does.
  ```
  (log "Hello" "World" :newline? false)
  ;;=> 03/08 10:42:10 HelloWorld:newline?false
  ```

**Comment by sirmspencer** [comment]
Would it be useful to create unit tests for these ns too?

triangulum.logging
triangulum.database
-- Unit tests will be done in a later PR.

triangulum.logging:

Line 9: Newline after output-path or remove newline on Line:8
Line 33: log-str doesn't support optional kwargs like log does.
-- Correct.  I dont plan on it either.

**Comment by Kcheung42** [comment]
Looks good, except for:

README.org:
- triangulum-build-db:
 - Mention the folders that the load functions target
 - Mention usage of toplevel sql comments (i.e. --NAMESPACE --REQUIRES)

**Pull request merged**
